### ISSUE TITLE
AM/PM doesn't show up on T-display option for 12 hour time format

### ISSUE THREAD

**Issue by spiff72** [kd8bxp/Cheerlights_Clock#1]
Hello

First of all - really nice project!  I have been playing with a TTGO T-display today that I ordered from Banggood, and found this project via thingiverse when looking for cases for it.  

It took me an hour to figure out I didn't have the T2 (and that I needed to comment ALL the alternate options out for the T-display to work.

I find however that the AM/PM indicator doesn't show up on my display when in 12 hour mode.  I probably will just use 24 hour mode because I like to see the seconds, but I can't figure out why I don't get the AM/PM indicator.

Also, can you clarify how often the weather data is updated and the time data is updated from the NTP server?  I can't figure this out from the code either...

Thanks!

**Comment by kd8bxp** [comment]
Hello, 
Thank you, glad you like it - So to answer a couple of your questions:

NTP and weather are updated about every 15 minutes give or take a few seconds (line 368)

The AM/PM maybe harder to work out - and I will have to break out a T-Display and see - it maybe something like display size not being set correctly, or ?? 
I'll see if I can work it out, and have to get back to you.

PS I like TTGO stuff, but it is hard to figure out which one is which....I feel your pain there.

**Comment by spiff72** [comment]
The real problem was that I didn't read the line stating that the default was the T-display!

And I see the line about the update period for the time and weather.  It wasn't 368, but close.  I added a few lines to PWM the backlight to see if I could get it to run longer on battery (just an experiment).

**Comment by kd8bxp** [comment]
But you are correct, AM/PM doesn't show up - now to figure out why. (or maybe what changed, I honestly can not remember if I checked it with this board), but I'll look into it and update if I know more.

**Comment by kd8bxp** [comment]
It appears to be a font issue, so the work around is to use a smaller font for the AM/PM on the T-display - I think it looks pretty good, but tell me what you think. Just updated the repository with the fix.

**Comment by spiff72** [comment]
Looks good - thanks for the update!  I am probably going to stick with the 24 hour time so I can keep the seconds in there.  Or I might play around with font sizes myself to squeeze in the AM/PM indicator with H:M:S all in place for the 12-hour when I get some more time to play with it.

**Comment by kd8bxp** [comment]
Just updated once more - added the seconds (small font) for AM/PM and the T-Display - give it one more try and see what you think, and if you find anything else let me, or if you make changes let me know, would love to see what you come up with. - Thanks

**Comment by spiff72** [comment]
Ok, thanks! I will load it up and try it out tomorrow.

**Comment by spiff72** [comment]
Just copied your updates into my version - looks good!

My only observation is that the 12 hour clock now looks a bit off, since it is left-justified on the display, while the other items (weather and date) are centered.  Can the 12 hour clock be centered too?  The 24 hour clock is OK like this because the seconds add some "length" that makes it look centered, but the 12 hour would look better if it was centered too.  

Just my $0.02 ...

Otherwise - thanks for your quick attention on this!

**Comment by spiff72** [comment]
I just tweaked the positions with the following in the code (basically shifted everything to the right by 40 pixels):

```
#else      
      tft.setTextColor(0x39C4, TFT_BLACK);
      //tft.drawString("88:88:88",10,10,7);
      tft.setTextColor(rgb565Decimal, TFT_BLACK);
      #ifdef HOUR12
      tft.drawString(timeString, 40, 0, 7);
      if (isAM()) { 
        tft.drawString("AM", 180,0,4); } else {
        tft.drawString("PM", 180,0,4); }
        char temp[5];
        sprintf (temp, ":%02i", second (t));
        tft.drawString(temp /*":" + (String)second (t)*/, 180, 25, 4);
```
I like this layout a lot.  I also found that the periodic updates are important for keeping accurate time.  I left mine for about 24 hours without an available wifi to connect to, and it lost about 15 minutes during that time.

Finally, I found another minor bug in the rendering.  During the time that I left it running overnight, there was a slight graphical glitch at the end of the date string on the display - noticeable mostly because it was a different color than the rest of the text.  My guess is that the date line of text got slightly shorter due to character widths changing (probably the M in Mon becoming a T, among others).  I think a full screen redraw might be needed right after midnight.

**Comment by spiff72** [comment]
Last thing - I changed the shift to 35 pixels - it still looked like 40 was too much:
```
#else      
      tft.setTextColor(0x39C4, TFT_BLACK);
     
      //tft.drawString("88:88:88",10,10,7);
      
      tft.setTextColor(rgb565Decimal, TFT_BLACK);
      #ifdef HOUR12
      tft.drawString(timeString, 35, 0, 7);
      if (isAM()) { 
        tft.drawString("AM", 175,0,4); } else {
        tft.drawString("PM", 175,0,4); }
        char temp[5];
        sprintf (temp, ":%02i", second (t));
        tft.drawString(temp /*":" + (String)second (t)*/, 175, 25, 4);   
```

I also added an if statement to check to see if it is midnight and if so, to do a fill screen with black:
```
String dayArray[9] = {"","Sun","Mon","Tue","Wed","Thr","Fri","Sat"};
String monthArray[14] = {"", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
String dateString = dayArray[weekday()] + " " + monthArray[month()] + " " + day() + ", " + year() + " ";
//Serial.print("Date: "); Serial.print(dayArray[weekday()]); Serial.print(" "); Serial.print(monthArray[month()]); Serial.print(" ");Serial.print(day()); Serial.print(", "); Serial.println(year());
if (hour(t)==0 || minute(t)==0 || second(t)==0) {
  tft.fillScreen(TFT_BLACK);
}
```
I am not sure if that will actually work, so will wait and see if it looks OK after a few nights pass.

**Comment by kd8bxp** [comment]
Sorry, I was busy all day today - so no time to "play" - But I think you are right, the offset of the display (all displays) in 12 hour mode is left justified and looks bad.  So I like what you have done there. 
Also yes, it will loose time if not connected, 15 minutes may be fast of a update, probably could get away with once every couple of hours calling the NTP server.  So that is probably (possible) something that I may change in the future, the NTP route also calls the weather update routine which I think you want to update more often - 15 minutes seemed like a good compromise there.
Screen glitches like you are talking about are a little hard to track down mostly because of what you say different widths of the characters, I thought we had that problem fixed with adding the background color of black, but again I think you are probably on the right track of maybe midnight and noon resetting the display and starting fresh.
Since I made this to work with different boards, I'd probably have the #ifdef in your check - I think only two of the boards use the tft.fillScreen(TFT_BLACK); method to clear the screen (I would have to look at that again) but good start there, you'll have to let me know if it works and I can get it into the main code.

In the next day or so I'll add in your display offset and update the code again - going to take me a couple of days (life is in the way)

**Comment by spiff72** [comment]
No rush!  I realized that I messed up the check for the hour minute and second to all be zero, and I noticed that it was causing a flicker in the display when the minute happened to be 00.  I used or operators instead of and...so I fixed that in the code below, and I moved it to the #else section that would only apply to the T-display:
```
      if (hour(t)==0 && minute(t)==0 && second(t)==0) {
      tft.fillScreen(TFT_BLACK);
      }
```
Again, I can't be sure this method will work (will it "catch" that 1 second of time when seconds, minutes and hour are all zero)?

**Comment by spiff72** [comment]
I just redid my check to the following - and confirmed that it worked by adjusting the values it checks the time against to the current time.  It actually redraws the screen when the seconds click to 01 and again at 02, then stops.
```
      //check to see if it is midnight, and if so, fill screen with black to eliminate any graphical
      //glitches that may have occurred from the changes to day/date line (variable character widths)
      if (hour(t)==0 && minute(t)==0 && (second(t)>0 && second(t)<3)) {
      tft.fillScreen(TFT_BLACK);
      }
```

I figured changing the seconds check to a range between 0 and 3 would guarantee that it works every time.
