### ISSUE TITLE
Bootlooping?

### ISSUE THREAD

**Issue by spiff72** [kd8bxp/Cheerlights_Clock#3]
Not sure what has happened - could be related to my own Arduino IDE, but I am no longer able to get this to run on my TTGO T-display.  I end up with bootloops (and the display either shows as black or just shows the last image that was on screen prior to uploading).

I have tried updating the TFT_eSPI library to latest version, and that doesn't work either.

I highly suspect that this is a problem on my end, but I just wanted to post this to confirm that it is still working on your end.  I am wondering if a library update or board update for the ESP32 may have borked it.

**Comment by kd8bxp** [comment]
can you post the output from the serial console?
I've seen boot loops when the spiffs gets reformated and the config file is missing - so that is where I'd probably start, but a lot of things can cause boot loops so the output should help narrow it down

**Comment by spiff72** [comment]
I completely forgot about the SPIFFS uploads.  I have several new boards and they likely didn't get that added.
I am also running this under Ubuntu now, and I just realized that the "tools" folder was empty.  I tried replacing the contents of that tools folder but I can't get the ESP sketch data upload menu to appear.  I will troubleshoot that tomorrow.  Here is the serial monitor data (I never saw the SPIFFS line in there because the monitor window was not very tall and it was not visible with all the reboots:
```
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
E (50) SPIFFS: mount failed, -10025
Failed to mount file system
Attempting MQTT connection.../home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088889 on core 1

Backtrace: 0x4008c454:0x3ffb1ce0 0x4008c685:0x3ffb1d00 0x40088889:0x3ffb1d20 0x4015e8ba:0x3ffb1d60 0x4015eb96:0x3ffb1d80 0x4014d558:0x3ffb1da0 0x4014d5c1:0x3ffb1dc0 0x40148bfe:0x3ffb1de0 0x4014772c:0x3ffb1e00 0x4014c6f0:0x3ffb1e40 0x400d6744:0x3ffb1e60 0x400d6106:0x3ffb1eb0 0x400d88c6:0x3ffb1ee0 0x400d8a9e:0x3ffb1f20 0x400d281f:0x3ffb1f50 0x400d28cf:0x3ffb1f90 0x400df60d:0x3ffb1fb0 0x40088b9d:0x3ffb1fd0

```

**Comment by kd8bxp** [comment]
Yes, I think SPIFFS is causing you issues - It's been a while since I setup the file system in the tools menu.  But I created a folder under the Arduino folder in your home folder. So mine looks like: /home/lfmiller/Arduino/tools .... that might help you.

**Comment by spiff72** [comment]
Update:  I still haven't been able to get the upload tool to show up under ubuntu - as far as I can tell the file structure is correct. 

I ended up switching to the Windows installation on my computer and that one is working.  I uploaded the data folder with the tool, and all is working again.  The arduino version on my windows installation is .10, while i just installed .12 on the Ubuntu side - maybe there is some incompatibility with the latest Arduino that is preventing the menu from appearing.

Thanks - I will close this out.

**Comment by spiff72** [comment]
Also - my arduino sketchbook is saved in my Google Drive, and I use a tool to sync that drive on the Ubuntu side as well, so theoretically they should be using the exact same sketchbook folder (and tools folder).  I do fight with some sync issues though, where library folders will get renamed, or appended with a "(1)" causing issues.  That might be a contributing factor too.

**Comment by kd8bxp** [comment]
I have mine synced using git - I am using 1.8.12 have not had a problem using the tool, but also installed that a while ago, probably under 1.8.5 (maybe) 
I honestly can't remember if I had problems installing this under linux or not - Linux file system is case sensitive (unlike Windows) IE:  /home/lfmiller/Arduino/tools or different from /home/lfmiller/Arduino/Tools (note the capital T )  Windows treats both like the same folder, linux says that it's two different folders - this has caused a few problems with some libraries - but it maybe  what you are seeing (??)

**Comment by spiff72** [comment]
I got it working under Ubuntu now - there was an extra folder level in there with a name like "ESP32".  I fixed that, and now I have two entries in Windows and one in Ubuntu!  It is working for now, so that is good. :-)  
I might have to look into using Git to sync them.  Google Drive can be a bit flaky, especially under Ubuntu since I use a 3rd party sync tool there (OverGrive).

Thanks!

**Comment by kd8bxp** [comment]
I gave up on google drive for linux years ago :-( 
GIT may not be the perfect choice either, it works for me - I use the app SmartGit to help - but GIT is all manual, not automatic so that is a draw back. 
You might look at syncthing or pcloud both work very well if you want a automatic sync. syncthing takes a little to setup but works great once it's done.

**Comment by spiff72** [comment]
Thanks - I have now set up Syncthing to give it a shot, using my RasPi4 as a sort of "hub" to serve up the files (always on).  Initially I ran into a snag because I couldn't sync between two partitions of my dual boot machine (Ubuntu and Windows).  The Pi made it work out nicely.
